# Copyright (C) 2024 Sebastien CHRISTIAN, University of French Polynesia
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import json
import os
from io import BytesIO
from typing import Any, Dict, Union, Optional
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill
from openpyxl.utils import get_column_letter
from openpyxl import load_workbook
import time


BASE_LD_PATH = os.path.join(os.getenv("RAILWAY_VOLUME_MOUNT_PATH", "./ld"), "storage")
CONVEQS_BASE_PATH = os.path.join(BASE_LD_PATH, "conveqs")
CONVEQS_ORIGINAL_FILES_PATH = os.path.join(CONVEQS_BASE_PATH, "original_files")
CONVEQS_TRANSPOSED_CQ_PATH = os.path.join(CONVEQS_BASE_PATH, "transposed_files")

def transposed_files_sanity_check():
    sanity_check = ""
    with open(os.path.join(CONVEQS_BASE_PATH, "conveqs_index.json"), "r") as cif:
        conveqs_index = json.load(cif)
        available_cqf = os.listdir(CONVEQS_TRANSPOSED_CQ_PATH)
    for entry in conveqs_index:
        expected_transposed_files = entry["transposed_as"]
        for etf in expected_transposed_files:
            if etf not in available_cqf:
                sanity_check += "; Entry {}: no {} file found despite being listed".format(entry["filename"], etf)
    return sanity_check


def catalog_transposed_conveqs_cqs():
    cq_catalog = []
    available_cqf = os.listdir(CONVEQS_TRANSPOSED_CQ_PATH)
    with open(os.path.join(CONVEQS_BASE_PATH, "conveqs_index.json"), "r") as cif:
        conveqs_index = json.load(cif)
    if available_cqf == []:
        return []
    else:
        sanity_check = transposed_files_sanity_check()
        if sanity_check != "":
            return ["transposed files sanity check failed"]
        else:
            for entry in conveqs_index:
                transposed_files_list = entry["transposed_as"]
                for tf in transposed_files_list:
                    tmp_item = entry
                    entry["cq"] = tf
                    cq_catalog.append(tmp_item)
        return cq_catalog



# ========== EXTRACT CQ JSON FROM XLS TEMPLATE ========================================

def _norm(s: Any) -> str:
    """Best-effort normalize to a clean string."""
    if s is None:
        return ""
    s = str(s)
    # preserve user content; just trim
    return s.strip()


def _read_info_kv(ws) -> Dict[str, str]:
    """
    Reads Info sheet key/value pairs that were written as:
      A5..: key, B5..: value
    """
    kv: Dict[str, str] = {}
    for row in ws.iter_rows(min_row=1, max_col=2):
        k = _norm(row[0].value)
        v = _norm(row[1].value) if len(row) > 1 else ""
        if k:
            kv[k] = v
    return kv


def _extract_uid_from_info(ws_info) -> str:
    """
    Builder wrote:
      A3 = f"“UID: {cq.get('uid', '')}”"
    so parse whatever is after UID:
    """
    a3 = _norm(ws_info["A3"].value)
    if not a3:
        return ""
    return a3[4:]

def conveqs_cq_translation_from_transcription_xlsx(
    xlsx,
    *,
    default_target_language: str = "target language",
):
    """
    Parse a completed CQ transcription workbook (generated by generate_transcription_xlsx)
    and return a CQ translation JSON dict.

    Parameters
    ----------
    xlsx:
        Path to .xlsx OR bytes OR BytesIO.

    default_target_language:
        Used if the Info sheet didn't specify a target language.
    """
    if isinstance(xlsx, (bytes, bytearray)):
        xlsx = BytesIO(xlsx)

    wb = load_workbook(xlsx, data_only=True)

    if "Info" not in wb.sheetnames:
        raise ValueError("Missing required sheet: 'Info'")
    if "Transcription" not in wb.sheetnames:
        raise ValueError("Missing required sheet: 'Transcription'")

    ws_info = wb["Info"]
    ws_t = wb["Transcription"]

    info_kv = _read_info_kv(ws_info)

    target_language = _norm(info_kv.get("Target language", "")) or default_target_language
    pivot_language = _norm(info_kv.get("Lingua franca", "")) or "English"

    transcription_made_by = _norm(info_kv.get("Language documenter", "missing"))
    content_provided_by = _norm(info_kv.get("Speaker(s)", "missing"))
    recording_date = _norm(info_kv.get("Recording date", "missing"))
    location = _norm(info_kv.get("Recording location", "missing")) or "unknown"

    # ---- Parse Transcription sheet ----

    data: Dict[str, Any] = {}

    # Iterate rows after header
    for r in ws_t.iter_rows(min_row=2, values_only=True):
        idx = _norm(r[0])
        english = _norm(r[1])
        pivot = _norm(r[2])
        target_sentence = _norm(r[3])
        notes = _norm(r[4])

        data[idx] = {
            "index": idx,
            "cq": english,
            "lingua franca": pivot,
            "translation": target_sentence,
            "comment": notes
        }

    # ---- Build final JSON ----
    interviewer = transcription_made_by or ""
    interviewee = content_provided_by or ""

    out = {
        "target language": target_language,
        "pivot language": pivot_language,
        "data": data,
        "interviewer": interviewer,
        "interviewee": interviewee,
        "location": location,
        "date": recording_date,
        "recording_uid": str(int(time.time())),
        "owner name": " and ".join([x for x in [interviewee, interviewer] if x]) or "",
        "authorization": "Creative Commons  CC BY-NC-ND 4.0",
    }

    return out