# Copyright (C) 2024 Sebastien CHRISTIAN, University of French Polynesia
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import json
import os
from io import BytesIO
from typing import Any, Dict, Union, Optional
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill
from openpyxl.utils import get_column_letter
from openpyxl import load_workbook
import time
import unicodedata


BASE_LD_PATH = os.path.join(os.getenv("RAILWAY_VOLUME_MOUNT_PATH", "./ld"), "storage")
CONVEQS_BASE_PATH = os.path.join(BASE_LD_PATH, "conveqs")
CONVEQS_ORIGINAL_FILES_PATH = os.path.join(CONVEQS_BASE_PATH, "original_files")
CONVEQS_TRANSPOSED_CQ_PATH = os.path.join(CONVEQS_BASE_PATH, "transposed_files")

def catalog_transposed_conveqs_cqs():
    tcq_list = []
    cq_catalog = []
    with open(os.path.join(CONVEQS_BASE_PATH, "conveqs_index.json"), "r") as cif:
        conveqs_index = json.load(cif)

    for item in conveqs_index:
       tcq_list += item["transposed_as"]

    directory_files = os.listdir(os.path.join(os.path.join(CONVEQS_TRANSPOSED_CQ_PATH)))
    normalized_files = [unicodedata.normalize("NFC", f) for f in directory_files]

    for filename in tcq_list:
        normalized_filename = unicodedata.normalize("NFC", filename)
        if normalized_filename in normalized_files:
            with open(os.path.join(CONVEQS_TRANSPOSED_CQ_PATH, filename), "r") as tcqf:
                f_content = json.load(tcqf)
                cq_catalog.append(
                    {"filename": filename,
                     "recording_uid": f_content["recording_uid"],
                     "title":  f_content["title"],
                     "language": f_content["language"],
                     "collection_date": f_content["collection_date"],
                     "collection_location": f_content["collection_location"],
                     "speaker": f_content["speaker"],
                     "language documenter": f_content["language documenter"],
                     "uploaded by": f_content["uploaded by"]
                    }
                )
        else:
            directory_files = os.listdir(os.path.join(os.path.join(CONVEQS_TRANSPOSED_CQ_PATH)))
            normalized_files = [unicodedata.normalize("NFC", f) for f in directory_files]
            normalized_filename = unicodedata.normalize("NFC", filename)
            print("Transposed file discrepancy")
            print("File {}".format(unicodedata.normalize("NFC", filename)))
            print("Not found in {}".format(", ".join([unicodedata.normalize("NFC", item) for item in directory_files])))
            # Print raw representations of the filename and directory files
            print("Filename being searched (repr):", repr(filename))
            print("Directory files (repr):", [repr(f) for f in directory_files])
            # Normalize filenames and compare
            normalized_filename = unicodedata.normalize("NFC", filename)
            normalized_files = [unicodedata.normalize("NFC", f) for f in directory_files]
            # Compare byte representations
            print("Filename bytes:", filename.encode("utf-8"))
            print("Directory file bytes:", [f.encode("utf-8") for f in directory_files])
    return cq_catalog

# ========== EXTRACT CQ JSON FROM XLS TEMPLATE ========================================

def _norm(s: Any) -> str:
    """Best-effort normalize to a clean string."""
    if s is None:
        return ""
    s = str(s)
    # preserve user content; just trim
    return s.strip()


def _read_info_kv(ws) -> Dict[str, str]:
    """
    Reads Info sheet key/value pairs that were written as:
      A5..: key, B5..: value
    """
    kv: Dict[str, str] = {}
    for row in ws.iter_rows(min_row=1, max_col=2):
        k = _norm(row[0].value)
        v = _norm(row[1].value) if len(row) > 1 else ""
        if k:
            kv[k] = v
    return kv


def _extract_uid_from_info(ws_info) -> str:
    """
    Builder wrote:
      A3 = f"“UID: {cq.get('uid', '')}”"
    so parse whatever is after UID:
    """
    a3 = _norm(ws_info["A3"].value)
    if not a3:
        return ""
    return a3[4:]

def conveqs_cq_translation_from_transcription_xlsx(xlsx):
    """
    Parse a completed CQ transcription workbook (generated by generate_transcription_xlsx)
    and return a CQ translation JSON dict.

    Parameters
    ----------
    xlsx:
        Path to .xlsx OR bytes OR BytesIO.

    """
    message = ""

    with open("./conveqs/canonical_cqs.json") as cf:
        canonical_cqs = json.load(cf)

    if isinstance(xlsx, (bytes, bytearray)):
        xlsx = BytesIO(xlsx)

    wb = load_workbook(xlsx, data_only=True)

    if "Info" not in wb.sheetnames:
        print("No Info tab in xls, returning message.")
        message = "No Info tab in xls"
        return None, message

    if "Transcription" not in wb.sheetnames:
        print("No Transcription tab in xls, returning message.")
        message = "No Transcription tab in xls"
        return None, message

    ws_info = wb["Info"]
    ws_t = wb["Transcription"]

    info_kv = _read_info_kv(ws_info)
    title = _norm(info_kv.get("Title", "No title found"))

    if title == "No title found":
        print("No title found, returning message.")
        message = "No title found"
        return None, message

    if title not in canonical_cqs.keys():
        print("CQ title unknown, returning message.")
        message = "CQ title unknown"
        return None, message
    else:
        canonical_cq = canonical_cqs[title]

    target_language = _norm(info_kv.get("Target language", "")) or default_target_language
    pivot_language = _norm(info_kv.get("Lingua franca", "")) or "English"

    transcription_made_by = _norm(info_kv.get("Language documenter", "missing"))
    content_provided_by = _norm(info_kv.get("Speaker(s)", "missing"))
    recording_date = _norm(info_kv.get("Recording date", "missing"))
    location = _norm(info_kv.get("Recording location", "missing")) or "unknown"

    # ---- Parse Transcription sheet ----

    data: Dict[str, Any] = {}

    # Iterate rows after header
    for r in ws_t.iter_rows(min_row=2, values_only=True):
        if _norm(r[0]) == "":
            break
        idx = _norm(r[0])
        english = _norm(r[2])
        pivot = _norm(r[3])
        target_sentence = _norm(r[4])
        notes = _norm(r[5])

        data[idx] = {
            "index": idx,
            "cq": english,
            "lingua franca": pivot,
            "translation": target_sentence,
            "comment": notes
        }
        try:
            expected_cq_sentence = [canonical["english"]
                                    for canonical in canonical_cq["dialog"]
                                    if canonical["index"] == idx][0]
        except IndexError:
            m1 = f"Empty list for expected sentence at idx {idx}"
            print(m1)
            return None, m1
        if english != expected_cq_sentence:
            m = "Sentence discrepancy between canonical and CQ document: {} vs {}".format(expected_cq_sentence, english)
            print(m)
            return None, m

    # ---- Build final JSON ----
    interviewer = transcription_made_by or ""
    interviewee = content_provided_by or ""

    out = {
        "title": title,
        "target language": target_language,
        "pivot language": pivot_language,
        "data": data,
        "recording_uid": str(int(time.time())),
        "authorization": "Creative Commons  CC BY-NC-ND 4.0",
    }

    return out, ""

